### ISSUE TITLE
NoMethodError: undefined method `push_key' for {}:Hash

### ISSUE THREAD

**Issue by koppen** [userlistio/userlist-ruby#1]
After updating from 0.3.0 to 0.4.0 our integration started failing with `NoMethodError: undefined method `push_key' for {}:Hash` error messages.

We've been configuring the Userlist::Client using ENV variables which has worked fine up until commit 88a40a2f8081babe7913ca3e4d91348bef87a148, it seems.

## On 0.3.0:

    [1] pry(main)> Userlist::Push::Client.new
    => #<Userlist::Push::Client:0x00007f8ee31e3998

## On 0.4.0:

    [1] pry(main)> Userlist::Push::Client.new
    NoMethodError: undefined method `push_key' for {}:Hash
     # ./lib/userlist/push/client.rb:14:in `initialize'

## Root cause

It seems the root cause is the difference between `config` and `@config` in

      def initialize(config = {})
        @config = Userlist.config.merge(config)

        raise Userlist::ConfigurationError, :push_key unless config.push_key
        raise Userlist::ConfigurationError, :push_endpoint unless config.push_endpoint
      end

## Next step?

I have pushed commit ebc91341b61380bb2ca4406cc174afa0169f043d to our fork, which demonstrates the issue. Now, I am not entirely sure what the preferred solution is, though.

I am leaning towards fixing the error, supporting the following methods of configuring Userlist::Client:

1. Using ENV
2. Using a Hash
3. Using a `Userlist::Config` object
4. and using `Userlist.configure`.

Alternatively we could probably cut some of those, reducing complexity and backwards compatibility.

In any case we should probably document the supported/suggested ways of configuring userlist in the README.

**Comment by benedikt** [comment]
@koppen Thanks a lot for this detailed bug report and sorry for causing this problem in the first place. I just pushed a new version that should fix it. Can you please try and let me know? Adding this line to your Gemfile should do the trick:

```ruby
gem 'userlist', git: 'https://github.com/userlistio/userlist-ruby', branch: 'master'
```

**Comment by koppen** [comment]
Dang, you beat me to the fix 😁 

That seems to do the trick for us, cheers!

And thanks for directing my attention to ENVCache, that seems very useful. I might just usurp that for some of our projects 👍

**Comment by benedikt** [comment]
Ok, cool! :) Will release the fix as v0.4.1
